services:
  backend:
    build:
      context: .
      dockerfile: Containerfile.dev
    environment:
      - DEBUG_MODE=true
    volumes:
      - .:/src/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
