FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git make gcc musl-dev curl
WORKDIR /src
RUN go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
ENTRYPOINT ["/src/entrypoint.sh"]